#!/usr/bin/python3
def raise_exception():
    print("{:d}".format(5 / "string"))
